version: 1.0.{build}
image: Visual Studio 2017
before_build:
  nuget restore
build:
  project: DiscriminatedUnion.csproj
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal